import type { Prompt } from "./data";

export const UPLOADED_PROMPTS: Prompt[] = [
  {
    id: "upl-01",
    image: "/uploads/added/just-do-it-concept-poster-no-5-05-03.jpg",
    model: "GPT Image",
    category: "Ads & Product",
    style: "Realistic",
    title: "'just Do It' Concept Poster No_ 5 [05.03",
    prompt: "'just Do It' Concept Poster No_ 5 [05.03. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1200,
    createdAt: "2026-09-10T13:10:07.093Z",
  },
  {
    id: "upl-02",
    image: "/uploads/added/1050464681854867912.jpg",
    model: "Nano Banana",
    category: "Posters & Visuals",
    style: "Filmic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1050464681854867912.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1337,
    createdAt: "2026-09-07T13:10:07.094Z",
  },
  {
    id: "upl-03",
    image: "/uploads/added/1084523154046459946.jpg",
    model: "Midjourney",
    category: "Illustration",
    style: "Editorial",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1084523154046459946.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1474,
    createdAt: "2026-09-04T13:10:07.095Z",
  },
  {
    id: "upl-04",
    image: "/uploads/added/1084523154046460017.jpg",
    model: "Seedance",
    category: "Characters",
    style: "Illustration",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1084523154046460017.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1611,
    createdAt: "2026-09-01T13:10:07.096Z",
  },
  {
    id: "upl-05",
    image: "/uploads/added/1084523154046460033.jpg",
    model: "Kling",
    category: "Fashion",
    style: "3D",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1084523154046460033.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1748,
    createdAt: "2026-08-29T13:10:07.097Z",
  },
  {
    id: "upl-06",
    image: "/uploads/added/1101763496404053350.jpg",
    model: "Gemini Omni",
    category: "Scenes",
    style: "Anime",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1101763496404053350.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1885,
    createdAt: "2026-08-26T13:10:07.098Z",
  },
  {
    id: "upl-07",
    image: "/uploads/added/1150106823621116617.jpg",
    model: "Grok",
    category: "Portraits",
    style: "Graphic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1150106823621116617.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2022,
    createdAt: "2026-08-23T13:10:07.099Z",
  },
  {
    id: "upl-08",
    image: "/uploads/added/144748575525411602.jpg",
    model: "MiniMax",
    category: "Ads & Product",
    style: "Retro",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 144748575525411602.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2159,
    createdAt: "2026-08-20T13:10:07.100Z",
  },
  {
    id: "upl-09",
    image: "/uploads/added/16114511161704513.jpg",
    model: "GPT Image",
    category: "Posters & Visuals",
    style: "Minimal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 16114511161704513.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2296,
    createdAt: "2026-08-17T13:10:07.101Z",
  },
  {
    id: "upl-10",
    image: "/uploads/added/339036678229531638.jpg",
    model: "Nano Banana",
    category: "Illustration",
    style: "Vintage",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 339036678229531638.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2433,
    createdAt: "2026-08-14T13:10:07.102Z",
  },
  {
    id: "upl-11",
    image: "/uploads/added/397020523423117615.jpg",
    model: "Midjourney",
    category: "Characters",
    style: "Cinematic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 397020523423117615.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2570,
    createdAt: "2026-09-08T13:10:07.103Z",
  },
  {
    id: "upl-12",
    image: "/uploads/added/4925880839655258.jpg",
    model: "Seedance",
    category: "Fashion",
    style: "Surreal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 4925880839655258.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2707,
    createdAt: "2026-09-05T13:10:07.104Z",
  },
  {
    id: "upl-13",
    image: "/uploads/added/550565123220867892.jpg",
    model: "Kling",
    category: "Scenes",
    style: "Storybook",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 550565123220867892.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2844,
    createdAt: "2026-09-02T13:10:07.105Z",
  },
  {
    id: "upl-14",
    image: "/uploads/added/556687203961676794.jpg",
    model: "Gemini Omni",
    category: "Portraits",
    style: "Realistic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 556687203961676794.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1281,
    createdAt: "2026-08-30T13:10:07.105Z",
  },
  {
    id: "upl-15",
    image: "/uploads/added/586312445286397274.jpg",
    model: "Grok",
    category: "Ads & Product",
    style: "Filmic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 586312445286397274.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1418,
    createdAt: "2026-08-27T13:10:07.106Z",
  },
  {
    id: "upl-16",
    image: "/uploads/added/625296729556647834.jpg",
    model: "MiniMax",
    category: "Posters & Visuals",
    style: "Editorial",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 625296729556647834.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1555,
    createdAt: "2026-08-24T13:10:07.107Z",
  },
  {
    id: "upl-17",
    image: "/uploads/added/679551031316320140.jpg",
    model: "GPT Image",
    category: "Illustration",
    style: "Illustration",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 679551031316320140.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1692,
    createdAt: "2026-08-21T13:10:07.108Z",
  },
  {
    id: "upl-18",
    image: "/uploads/added/682084306103541230.jpg",
    model: "Nano Banana",
    category: "Characters",
    style: "3D",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 682084306103541230.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1829,
    createdAt: "2026-08-18T13:10:07.109Z",
  },
  {
    id: "upl-19",
    image: "/uploads/added/683421312250799649.jpg",
    model: "Midjourney",
    category: "Fashion",
    style: "Anime",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 683421312250799649.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1966,
    createdAt: "2026-08-15T13:10:07.110Z",
  },
  {
    id: "upl-20",
    image: "/uploads/added/686236062018415528.jpg",
    model: "Seedance",
    category: "Scenes",
    style: "Graphic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 686236062018415528.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2103,
    createdAt: "2026-09-09T13:10:07.111Z",
  },
  {
    id: "upl-21",
    image: "/uploads/added/720716746684579681.jpg",
    model: "Kling",
    category: "Portraits",
    style: "Retro",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 720716746684579681.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2240,
    createdAt: "2026-09-06T13:10:07.112Z",
  },
  {
    id: "upl-22",
    image: "/uploads/added/76561262411906623.jpg",
    model: "Gemini Omni",
    category: "Ads & Product",
    style: "Minimal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 76561262411906623.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2377,
    createdAt: "2026-09-03T13:10:07.113Z",
  },
  {
    id: "upl-23",
    image: "/uploads/added/778208010655965500.jpg",
    model: "Grok",
    category: "Posters & Visuals",
    style: "Vintage",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 778208010655965500.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2514,
    createdAt: "2026-08-31T13:10:07.115Z",
  },
  {
    id: "upl-24",
    image: "/uploads/added/778700591867839798.jpg",
    model: "MiniMax",
    category: "Illustration",
    style: "Cinematic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 778700591867839798.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2651,
    createdAt: "2026-08-28T13:10:07.116Z",
  },
  {
    id: "upl-25",
    image: "/uploads/added/807129564511879645.jpg",
    model: "GPT Image",
    category: "Characters",
    style: "Surreal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 807129564511879645.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 2788,
    createdAt: "2026-08-25T13:10:07.117Z",
  },
  {
    id: "upl-26",
    image: "/uploads/added/857654322833620068.jpg",
    model: "Nano Banana",
    category: "Fashion",
    style: "Storybook",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 857654322833620068.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1225,
    createdAt: "2026-08-22T13:10:07.118Z",
  },
  {
    id: "upl-27",
    image: "/uploads/added/865254147178359519.jpg",
    model: "Midjourney",
    category: "Scenes",
    style: "Realistic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 865254147178359519.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1362,
    createdAt: "2026-08-19T13:10:07.119Z",
  },
  {
    id: "upl-28",
    image: "/uploads/added/901775525406717821.jpg",
    model: "Seedance",
    category: "Portraits",
    style: "Filmic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 901775525406717821.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1499,
    createdAt: "2026-08-16T13:10:07.120Z",
  },
  {
    id: "upl-29",
    image: "/uploads/added/95912667061728781.jpg",
    model: "Kling",
    category: "Ads & Product",
    style: "Editorial",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 95912667061728781.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1636,
    createdAt: "2026-09-10T13:10:07.121Z",
  },
  {
    id: "upl-30",
    image: "/uploads/added/981221837582334474.jpg",
    model: "Gemini Omni",
    category: "Posters & Visuals",
    style: "Illustration",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 981221837582334474.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1773,
    createdAt: "2026-09-07T13:10:07.122Z",
  },
  {
    id: "upl-31",
    image: "/uploads/added/992269730415513234.jpg",
    model: "Grok",
    category: "Illustration",
    style: "3D",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 992269730415513234.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1910,
    createdAt: "2026-09-04T13:10:07.124Z",
  },
  {
    id: "upl-32",
    image: "/uploads/added/adorable-alpaca-in-meadow.jpg",
    model: "MiniMax",
    category: "Characters",
    style: "Anime",
    title: "Adorable Alpaca In Meadow",
    prompt: "Adorable Alpaca In Meadow. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2047,
    createdAt: "2026-09-01T13:10:07.125Z",
  },
  {
    id: "upl-33",
    image: "/uploads/added/adorable-fluffy-white-bunny-with-cherry-blossoms.jpg",
    model: "GPT Image",
    category: "Fashion",
    style: "Graphic",
    title: "Adorable Fluffy White Bunny With Cherry Blossoms",
    prompt: "Adorable Fluffy White Bunny With Cherry Blossoms. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2184,
    createdAt: "2026-08-29T13:10:07.126Z",
  },
  {
    id: "upl-34",
    image: "/uploads/added/adorable-tiger-cub-in-snow-cute-baby-tiger.jpg",
    model: "Nano Banana",
    category: "Scenes",
    style: "Retro",
    title: "Adorable Tiger Cub In Snow _ Cute Baby",
    prompt: "Adorable Tiger Cub In Snow _ Cute Baby. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2321,
    createdAt: "2026-08-26T13:10:07.128Z",
  },
  {
    id: "upl-35",
    image: "/uploads/added/ahhhh-cutis.jpg",
    model: "Midjourney",
    category: "Portraits",
    style: "Minimal",
    title: "Ahhhh Cutis",
    prompt: "Ahhhh Cutis. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2458,
    createdAt: "2026-08-23T13:10:07.129Z",
  },
  {
    id: "upl-36",
    image: "/uploads/added/animated-stickers.jpg",
    model: "Seedance",
    category: "Ads & Product",
    style: "Vintage",
    title: "Animated Stickers",
    prompt: "Animated Stickers. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2595,
    createdAt: "2026-08-20T13:10:07.130Z",
  },
  {
    id: "upl-37",
    image: "/uploads/added/b000419263693el-jpg-19202656.jpg",
    model: "Kling",
    category: "Posters & Visuals",
    style: "Cinematic",
    title: "B000419263693el_jpg (19202656)",
    prompt: "B000419263693el_jpg (19202656). High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2732,
    createdAt: "2026-08-17T13:10:07.131Z",
  },
  {
    id: "upl-38",
    image: "/uploads/added/can-we-talk-about-how-happy-they-still-are.jpg",
    model: "Gemini Omni",
    category: "Illustration",
    style: "Surreal",
    title: "Can We Talk About How Happy They Still",
    prompt: "Can We Talk About How Happy They Still. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2869,
    createdAt: "2026-08-14T13:10:07.132Z",
  },
  {
    id: "upl-39",
    image: "/uploads/added/cat-1.jpg",
    model: "Grok",
    category: "Characters",
    style: "Storybook",
    title: "Cat 1",
    prompt: "Cat 1. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1306,
    createdAt: "2026-09-08T13:10:07.133Z",
  },
  {
    id: "upl-40",
    image: "/uploads/added/cat-abstract.jpg",
    model: "MiniMax",
    category: "Fashion",
    style: "Realistic",
    title: "Cat Abstract",
    prompt: "Cat Abstract. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1443,
    createdAt: "2026-09-05T13:10:07.134Z",
  },
  {
    id: "upl-41",
    image: "/uploads/added/child-at-playground-ads-playful-childrens-advertising-advertising-campaign-for-kids-lego.jpg",
    model: "GPT Image",
    category: "Scenes",
    style: "Filmic",
    title: "Child At Playground Ads _ Playful Childrens Advertising,",
    prompt: "Child At Playground Ads _ Playful Childrens Advertising,. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1580,
    createdAt: "2026-09-02T13:10:07.135Z",
  },
  {
    id: "upl-42",
    image: "/uploads/added/creative-minds-work-outside-the-lines-where-bold.jpg",
    model: "Nano Banana",
    category: "Portraits",
    style: "Editorial",
    title: "Creative Minds Work Outside The Lines Where Bold",
    prompt: "Creative Minds Work Outside The Lines Where Bold. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1717,
    createdAt: "2026-08-30T13:10:07.137Z",
  },
  {
    id: "upl-43",
    image: "/uploads/added/cute-baby-snub-nosed-monkey.jpg",
    model: "Midjourney",
    category: "Ads & Product",
    style: "Illustration",
    title: "Cute Baby Snub Nosed Monkey",
    prompt: "Cute Baby Snub Nosed Monkey. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1854,
    createdAt: "2026-08-27T13:10:07.138Z",
  },
  {
    id: "upl-44",
    image: "/uploads/added/dyson-headphones-dyson-dyson-zone-dual-ndfeb-wireless-headphones-air-purifier-ultra-blue-color-blue-size-os.jpg",
    model: "Seedance",
    category: "Posters & Visuals",
    style: "3D",
    title: "Dyson Headphones _ Dyson - Dyson Zone Dual",
    prompt: "Dyson Headphones _ Dyson - Dyson Zone Dual. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1991,
    createdAt: "2026-08-24T13:10:07.139Z",
  },
  {
    id: "upl-45",
    image: "/uploads/added/feral-prism.jpg",
    model: "Kling",
    category: "Illustration",
    style: "Anime",
    title: "Feral Prism",
    prompt: "Feral Prism. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2128,
    createdAt: "2026-08-21T13:10:07.140Z",
  },
  {
    id: "upl-46",
    image: "/uploads/added/golden-retriever-puppy-pure-sunshine-in-fur.jpg",
    model: "Gemini Omni",
    category: "Characters",
    style: "Graphic",
    title: "Golden Retriever Puppy_ Pure Sunshine In Fur!",
    prompt: "Golden Retriever Puppy_ Pure Sunshine In Fur!. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2265,
    createdAt: "2026-08-18T13:10:07.140Z",
  },
  {
    id: "upl-47",
    image: "/uploads/added/instagram-1.jpg",
    model: "Grok",
    category: "Fashion",
    style: "Retro",
    title: "Instagram (1)",
    prompt: "Instagram (1). High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2402,
    createdAt: "2026-08-15T13:10:07.141Z",
  },
  {
    id: "upl-48",
    image: "/uploads/added/instagram.jpg",
    model: "MiniMax",
    category: "Scenes",
    style: "Minimal",
    title: "Instagram",
    prompt: "Instagram. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2539,
    createdAt: "2026-09-09T13:10:07.142Z",
  },
  {
    id: "upl-49",
    image: "/uploads/added/los-corredores-frondoso.jpg",
    model: "GPT Image",
    category: "Portraits",
    style: "Vintage",
    title: "Los Corredores Frondoso",
    prompt: "Los Corredores Frondoso. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2676,
    createdAt: "2026-09-06T13:10:07.143Z",
  },
  {
    id: "upl-50",
    image: "/uploads/added/neue-swiss-8-weight-swiss-sans-leasted-graphics-template-resources.jpg",
    model: "Nano Banana",
    category: "Ads & Product",
    style: "Cinematic",
    title: "Neue Swiss _ 8 Weight Swiss Sans -",
    prompt: "Neue Swiss _ 8 Weight Swiss Sans -. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2813,
    createdAt: "2026-09-03T13:10:07.144Z",
  },
  {
    id: "upl-51",
    image: "/uploads/added/so-whenever-you-are-wherever-you-go-always-bring.jpg",
    model: "Midjourney",
    category: "Posters & Visuals",
    style: "Surreal",
    title: "So Whenever You Are, Wherever You Go Always",
    prompt: "So Whenever You Are, Wherever You Go Always. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1250,
    createdAt: "2026-08-31T13:10:07.145Z",
  },
  {
    id: "upl-52",
    image: "/uploads/added/swiss-design-poster-international-typographic-art-graphic-style.jpg",
    model: "Seedance",
    category: "Illustration",
    style: "Storybook",
    title: "Swiss Design Poster_ International Typographic Art & Graphic",
    prompt: "Swiss Design Poster_ International Typographic Art & Graphic. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1387,
    createdAt: "2026-08-28T13:10:07.146Z",
  },
  {
    id: "upl-53",
    image: "/uploads/added/swiss-style-grid-layout-poster-display-fonts-transform-your-design.jpg",
    model: "Kling",
    category: "Characters",
    style: "Realistic",
    title: "Swiss Style Grid Layout Poster Display Fonts Transform",
    prompt: "Swiss Style Grid Layout Poster Display Fonts Transform. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1524,
    createdAt: "2026-08-25T13:10:07.147Z",
  },
  {
    id: "upl-54",
    image: "/uploads/added/tom-the-lizard-phone-wallpaper.jpg",
    model: "Gemini Omni",
    category: "Fashion",
    style: "Filmic",
    title: "Tom The Lizard Phone Wallpaper_",
    prompt: "Tom The Lizard Phone Wallpaper_. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1661,
    createdAt: "2026-08-22T13:10:07.148Z",
  },
  {
    id: "upl-55",
    image: "/uploads/added/turn-heads-with-product-animation-motion-design-for-brands.jpg",
    model: "Grok",
    category: "Scenes",
    style: "Editorial",
    title: "Turn Heads With Product Animation _ Motion Design",
    prompt: "Turn Heads With Product Animation _ Motion Design. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1798,
    createdAt: "2026-08-19T13:10:07.149Z",
  },
  {
    id: "upl-56",
    image: "/uploads/added/two-cats-are-lying-on-the-table-one-is-an-american-shorthair-cat-and-the-other-is-a-white-cat.jpg",
    model: "MiniMax",
    category: "Portraits",
    style: "Illustration",
    title: "Two Cats Are Lying On The Table, One",
    prompt: "Two Cats Are Lying On The Table, One. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1935,
    createdAt: "2026-08-16T13:10:07.150Z",
  },
  {
    id: "upl-57",
    image: "/uploads/added/user-error-404.jpg",
    model: "GPT Image",
    category: "Ads & Product",
    style: "3D",
    title: "User Error 404",
    prompt: "User Error 404. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2072,
    createdAt: "2026-09-10T13:10:07.151Z",
  },
  {
    id: "upl-58",
    image: "/uploads/added/valere-brain-graph-tyler-gpt-5-5.jpg",
    model: "Nano Banana",
    category: "Posters & Visuals",
    style: "Anime",
    title: "Valere Brain Graph (tyler Gpt 5_5)",
    prompt: "Valere Brain Graph (tyler Gpt 5_5). High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2209,
    createdAt: "2026-09-07T13:10:07.152Z",
  },
  {
    id: "upl-59",
    image: "/uploads/added/the-curious-duck-family.jpg",
    model: "Midjourney",
    category: "Illustration",
    style: "Graphic",
    title: "[] ; The Curious Duck Family",
    prompt: "[] ; The Curious Duck Family. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2346,
    createdAt: "2026-09-04T13:10:07.153Z",
  },
  {
    id: "upl-60",
    image: "/uploads/added/cute-ducky.jpg",
    model: "Seedance",
    category: "Characters",
    style: "Retro",
    title: "Cute Ducky",
    prompt: "Cute Ducky. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2483,
    createdAt: "2026-09-01T13:10:07.154Z",
  },
  {
    id: "upl-61",
    image: "/uploads/added/download-3.jpg",
    model: "Kling",
    category: "Fashion",
    style: "Minimal",
    title: "Download (3)",
    prompt: "Download (3). High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2620,
    createdAt: "2026-08-29T13:10:07.155Z",
  },
  {
    id: "upl-62",
    image: "/uploads/added/editing-graphics-inspiration-day-3-video-editor-or-graphic.jpg",
    model: "Gemini Omni",
    category: "Scenes",
    style: "Vintage",
    title: "Editing Graphics Inspiration Day 3 Video Editor Or",
    prompt: "Editing Graphics Inspiration Day 3 Video Editor Or. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2757,
    createdAt: "2026-08-26T13:10:07.156Z",
  },
  {
    id: "upl-63",
    image: "/uploads/added/product.jpg",
    model: "Grok",
    category: "Portraits",
    style: "Cinematic",
    title: "Product",
    prompt: "Product. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 2894,
    createdAt: "2026-08-23T13:10:07.157Z",
  },
  {
    id: "upl-64",
    image: "/uploads/added/image.jpg",
    model: "MiniMax",
    category: "Ads & Product",
    style: "Surreal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - карликовоя коза🐐🐐🤘.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1331,
    createdAt: "2026-08-20T13:10:07.158Z",
  },
  {
    id: "upl-65",
    image: "/uploads/added/image-2.jpg",
    model: "GPT Image",
    category: "Posters & Visuals",
    style: "Storybook",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - ….jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1468,
    createdAt: "2026-08-17T13:10:07.159Z",
  }
];
