import type { Prompt } from "./data";

export const REAL_PROMPTS: Prompt[] = [
  {
    id: "real-01",
    image: "/uploads/real/1018798747005650491.jpg",
    model: "GPT Image",
    category: "Ads & Product",
    style: "Realistic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1018798747005650491.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1793,
    createdAt: "2026-08-23T13:27:16.336Z",
  },
  {
    id: "real-02",
    image: "/uploads/real/1053701644086119011.jpg",
    model: "Nano Banana",
    category: "Posters & Visuals",
    style: "Filmic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1053701644086119011.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1889,
    createdAt: "2026-08-27T13:27:16.336Z",
  },
  {
    id: "real-03",
    image: "/uploads/real/1104648614876048059.jpg",
    model: "Midjourney",
    category: "Illustration",
    style: "Editorial",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1104648614876048059.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1704,
    createdAt: "2026-09-08T13:27:16.336Z",
  },
  {
    id: "real-04",
    image: "/uploads/real/1117596463799454064.jpg",
    model: "Seedance",
    category: "Characters",
    style: "Illustration",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1117596463799454064.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1729,
    createdAt: "2026-09-04T13:27:16.336Z",
  },
  {
    id: "real-05",
    image: "/uploads/real/1143069949190887785.jpg",
    model: "Kling",
    category: "Fashion",
    style: "3D",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1143069949190887785.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1215,
    createdAt: "2026-09-08T13:27:16.336Z",
  },
  {
    id: "real-06",
    image: "/uploads/real/1147573548785383484.jpg",
    model: "Gemini Omni",
    category: "Scenes",
    style: "Anime",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 1147573548785383484.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 294,
    createdAt: "2026-09-07T13:27:16.336Z",
  },
  {
    id: "real-07",
    image: "/uploads/real/2089291663466508680-1.jpg",
    model: "Grok",
    category: "Portraits",
    style: "Graphic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 2089291663466508680-1.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1070,
    createdAt: "2026-08-15T13:27:16.336Z",
  },
  {
    id: "real-08",
    image: "/uploads/real/429530883226307399.jpg",
    model: "MiniMax",
    category: "Ads & Product",
    style: "Retro",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 429530883226307399.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1114,
    createdAt: "2026-08-25T13:27:16.336Z",
  },
  {
    id: "real-09",
    image: "/uploads/real/474707616989469126.jpg",
    model: "GPT Image",
    category: "Posters & Visuals",
    style: "Minimal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 474707616989469126.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 352,
    createdAt: "2026-09-01T13:27:16.336Z",
  },
  {
    id: "real-10",
    image: "/uploads/real/474707616989517622.jpg",
    model: "Nano Banana",
    category: "Illustration",
    style: "Vintage",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 474707616989517622.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 396,
    createdAt: "2026-08-11T13:27:16.336Z",
  },
  {
    id: "real-11",
    image: "/uploads/real/51158145760701899.jpg",
    model: "Midjourney",
    category: "Characters",
    style: "Cinematic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 51158145760701899.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 695,
    createdAt: "2026-08-28T13:27:16.336Z",
  },
  {
    id: "real-12",
    image: "/uploads/real/574560864938971320.jpg",
    model: "Seedance",
    category: "Fashion",
    style: "Surreal",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 574560864938971320.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1870,
    createdAt: "2026-08-19T13:27:16.336Z",
  },
  {
    id: "real-13",
    image: "/uploads/real/58617232657824427.jpg",
    model: "Kling",
    category: "Scenes",
    style: "Storybook",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 58617232657824427.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 880,
    createdAt: "2026-08-26T13:27:16.336Z",
  },
  {
    id: "real-14",
    image: "/uploads/real/663999538840870998.jpg",
    model: "Gemini Omni",
    category: "Portraits",
    style: "Realistic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 663999538840870998.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1802,
    createdAt: "2026-08-28T13:27:16.336Z",
  },
  {
    id: "real-15",
    image: "/uploads/real/702280135686359018.jpg",
    model: "Grok",
    category: "Ads & Product",
    style: "Filmic",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 702280135686359018.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1138,
    createdAt: "2026-08-26T13:27:16.336Z",
  },
  {
    id: "real-16",
    image: "/uploads/real/739857045074206141.jpg",
    model: "MiniMax",
    category: "Posters & Visuals",
    style: "Editorial",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 739857045074206141.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1680,
    createdAt: "2026-08-30T13:27:16.336Z",
  },
  {
    id: "real-17",
    image: "/uploads/real/819092251024801158.jpg",
    model: "GPT Image",
    category: "Illustration",
    style: "Illustration",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 819092251024801158.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1138,
    createdAt: "2026-09-07T13:27:16.336Z",
  },
  {
    id: "real-18",
    image: "/uploads/real/859835753916497675.jpg",
    model: "Nano Banana",
    category: "Characters",
    style: "3D",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 859835753916497675.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1537,
    createdAt: "2026-09-08T13:27:16.336Z",
  },
  {
    id: "real-19",
    image: "/uploads/real/956733514606769462.jpg",
    model: "Midjourney",
    category: "Fashion",
    style: "Anime",
    title: "Untitled capture",
    prompt: "High-quality AI generated image - 956733514606769462.jpg. Detailed prompt not yet added. Describe the subject, lighting, style, and composition in detail for the best results.",
    likes: 1562,
    createdAt: "2026-09-07T13:27:16.336Z",
  },
  {
    id: "real-20",
    image: "/uploads/real/a-mans-face-is-shown-in-the-air-with-clouds-around-him-and-his-head-has-been-cut.jpg",
    model: "Seedance",
    category: "Scenes",
    style: "Graphic",
    title: "A Mans Face Is Shown In The Air",
    prompt: "A Mans Face Is Shown In The Air. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 898,
    createdAt: "2026-08-30T13:27:16.336Z",
  },
  {
    id: "real-21",
    image: "/uploads/real/artzchillect-artzchillect-on-x.jpg",
    model: "Kling",
    category: "Portraits",
    style: "Retro",
    title: "Artzchillect Artzchillect On X",
    prompt: "Artzchillect Artzchillect On X. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1341,
    createdAt: "2026-08-24T13:27:16.336Z",
  },
  {
    id: "real-22",
    image: "/uploads/real/blinged-out-croc.jpg",
    model: "Gemini Omni",
    category: "Ads & Product",
    style: "Minimal",
    title: "Blinged Out Croc",
    prompt: "Blinged Out Croc. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 506,
    createdAt: "2026-08-29T13:27:16.336Z",
  },
  {
    id: "real-23",
    image: "/uploads/real/dilver-surfer.jpg",
    model: "Grok",
    category: "Posters & Visuals",
    style: "Vintage",
    title: "Dilver Surfer",
    prompt: "Dilver Surfer. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1040,
    createdAt: "2026-08-20T13:27:16.336Z",
  },
  {
    id: "real-24",
    image: "/uploads/real/download-1.jpg",
    model: "MiniMax",
    category: "Illustration",
    style: "Cinematic",
    title: "Download 1",
    prompt: "Download 1. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 700,
    createdAt: "2026-08-20T13:27:16.336Z",
  },
  {
    id: "real-25",
    image: "/uploads/real/download-2.jpg",
    model: "GPT Image",
    category: "Characters",
    style: "Surreal",
    title: "Download 2",
    prompt: "Download 2. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 747,
    createdAt: "2026-08-13T13:27:16.336Z",
  },
  {
    id: "real-26",
    image: "/uploads/real/download-3.jpg",
    model: "Nano Banana",
    category: "Fashion",
    style: "Storybook",
    title: "Download 3",
    prompt: "Download 3. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 581,
    createdAt: "2026-08-14T13:27:16.336Z",
  },
  {
    id: "real-27",
    image: "/uploads/real/download-4.jpg",
    model: "Midjourney",
    category: "Scenes",
    style: "Realistic",
    title: "Download 4",
    prompt: "Download 4. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1492,
    createdAt: "2026-08-25T13:27:16.336Z",
  },
  {
    id: "real-28",
    image: "/uploads/real/download-5.jpg",
    model: "Seedance",
    category: "Portraits",
    style: "Filmic",
    title: "Download 5",
    prompt: "Download 5. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 788,
    createdAt: "2026-08-30T13:27:16.336Z",
  },
  {
    id: "real-29",
    image: "/uploads/real/funny-cat-chromakey-cutouts-for-editing-video.jpg",
    model: "Kling",
    category: "Ads & Product",
    style: "Editorial",
    title: "Funny Cat Chromakey Cutouts For Editing Video",
    prompt: "Funny Cat Chromakey Cutouts For Editing Video. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1920,
    createdAt: "2026-09-02T13:27:16.336Z",
  },
  {
    id: "real-30",
    image: "/uploads/real/good-vibes-sign_ozon-bank.jpg",
    model: "Gemini Omni",
    category: "Posters & Visuals",
    style: "Illustration",
    title: "Good Vibes Sign Ozon Bank",
    prompt: "Good Vibes Sign Ozon Bank. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1455,
    createdAt: "2026-08-16T13:27:16.336Z",
  },
  {
    id: "real-31",
    image: "/uploads/real/just-made-this-awesome-ai-art-with-piclumen.jpg",
    model: "Grok",
    category: "Illustration",
    style: "3D",
    title: "Just Made This Awesome Ai Art With Piclumen",
    prompt: "Just Made This Awesome Ai Art With Piclumen. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1256,
    createdAt: "2026-08-25T13:27:16.336Z",
  },
  {
    id: "real-32",
    image: "/uploads/real/lol-background.jpg",
    model: "MiniMax",
    category: "Characters",
    style: "Anime",
    title: "Lol Background",
    prompt: "Lol Background. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1704,
    createdAt: "2026-09-01T13:27:16.336Z",
  },
  {
    id: "real-33",
    image: "/uploads/real/monkey-cries.jpg",
    model: "GPT Image",
    category: "Fashion",
    style: "Graphic",
    title: "Monkey Cries",
    prompt: "Monkey Cries. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1109,
    createdAt: "2026-09-08T13:27:16.336Z",
  },
  {
    id: "real-34",
    image: "/uploads/real/nano-banana-studio-backdrop-light-prompt.jpg",
    model: "Nano Banana",
    category: "Scenes",
    style: "Retro",
    title: "Nano Banana Studio Backdrop Light Prompt",
    prompt: "Nano Banana Studio Backdrop Light Prompt. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 360,
    createdAt: "2026-09-07T13:27:16.336Z",
  },
  {
    id: "real-35",
    image: "/uploads/real/peeking-pet-box-_-smart-prompt.jpg",
    model: "Midjourney",
    category: "Portraits",
    style: "Minimal",
    title: "Peeking Pet Box Smart Prompt",
    prompt: "Peeking Pet Box Smart Prompt. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 400,
    createdAt: "2026-08-12T13:27:16.336Z",
  },
  {
    id: "real-36",
    image: "/uploads/real/pepe-the-frog-1.jpg",
    model: "Seedance",
    category: "Ads & Product",
    style: "Vintage",
    title: "Pepe The Frog 1",
    prompt: "Pepe The Frog 1. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 683,
    createdAt: "2026-09-06T13:27:16.336Z",
  },
  {
    id: "real-37",
    image: "/uploads/real/pepe-the-frog.jpg",
    model: "Kling",
    category: "Posters & Visuals",
    style: "Cinematic",
    title: "Pepe The Frog",
    prompt: "Pepe The Frog. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1924,
    createdAt: "2026-08-19T13:27:16.336Z",
  },
  {
    id: "real-38",
    image: "/uploads/real/safe-image-01.jpg",
    model: "Gemini Omni",
    category: "Illustration",
    style: "Surreal",
    title: "Safe Image 01",
    prompt: "Safe Image 01. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1427,
    createdAt: "2026-08-25T13:27:16.336Z",
  },
  {
    id: "real-39",
    image: "/uploads/real/safe-image-02.jpg",
    model: "Grok",
    category: "Characters",
    style: "Storybook",
    title: "Safe Image 02",
    prompt: "Safe Image 02. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 498,
    createdAt: "2026-08-10T13:27:16.336Z",
  },
  {
    id: "real-40",
    image: "/uploads/real/safe-image-03.jpg",
    model: "MiniMax",
    category: "Fashion",
    style: "Realistic",
    title: "Safe Image 03",
    prompt: "Safe Image 03. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1116,
    createdAt: "2026-08-18T13:27:16.336Z",
  },
  {
    id: "real-41",
    image: "/uploads/real/sculpture-posing-in-a-nonchalant-way-design-.jpg",
    model: "GPT Image",
    category: "Scenes",
    style: "Filmic",
    title: "Sculpture Posing In A Nonchalant Way Design",
    prompt: "Sculpture Posing In A Nonchalant Way Design. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1648,
    createdAt: "2026-08-25T13:27:16.336Z",
  },
  {
    id: "real-42",
    image: "/uploads/real/sleep-emoji.jpg",
    model: "Nano Banana",
    category: "Portraits",
    style: "Editorial",
    title: "Sleep Emoji",
    prompt: "Sleep Emoji. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1986,
    createdAt: "2026-08-29T13:27:16.336Z",
  },
  {
    id: "real-43",
    image: "/uploads/real/sometimes-his-cuteness-turns-into-cheekiness-the_goats_that_cud-animallover-anim.jpg",
    model: "Midjourney",
    category: "Ads & Product",
    style: "Illustration",
    title: "Sometimes His Cuteness Turns Into Cheekiness The Goats",
    prompt: "Sometimes His Cuteness Turns Into Cheekiness The Goats. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1723,
    createdAt: "2026-08-15T13:27:16.336Z",
  },
  {
    id: "real-44",
    image: "/uploads/real/stoic-aesthetics.jpg",
    model: "Seedance",
    category: "Posters & Visuals",
    style: "3D",
    title: "Stoic Aesthetics",
    prompt: "Stoic Aesthetics. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 1789,
    createdAt: "2026-09-07T13:27:16.336Z",
  },
  {
    id: "real-45",
    image: "/uploads/real/surreal-ai-portrait-visual-for-creative-campaign.jpg",
    model: "Kling",
    category: "Illustration",
    style: "Anime",
    title: "Surreal Ai Portrait Visual For Creative Campaign",
    prompt: "Surreal Ai Portrait Visual For Creative Campaign. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 458,
    createdAt: "2026-08-11T13:27:16.336Z",
  },
  {
    id: "real-46",
    image: "/uploads/real/the-infinite-world-of-tennis-.jpg",
    model: "Gemini Omni",
    category: "Characters",
    style: "Graphic",
    title: "The Infinite World Of Tennis",
    prompt: "The Infinite World Of Tennis. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 622,
    createdAt: "2026-08-29T13:27:16.336Z",
  },
  {
    id: "real-47",
    image: "/uploads/real/we-leave-impact-just-with-your-design.jpg",
    model: "Grok",
    category: "Fashion",
    style: "Retro",
    title: "We Leave Impact Just With Your Design",
    prompt: "We Leave Impact Just With Your Design. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 281,
    createdAt: "2026-09-02T13:27:16.336Z",
  },
  {
    id: "real-48",
    image: "/uploads/real/yellow-ice-cream-park-summer-time-3d-typography.jpg",
    model: "MiniMax",
    category: "Scenes",
    style: "Minimal",
    title: "Yellow Ice Cream Park Summer Time 3d Typography",
    prompt: "Yellow Ice Cream Park Summer Time 3d Typography. High-resolution, detailed, professional composition with careful lighting, texture, and color. Commercial-grade image prompt.",
    likes: 224,
    createdAt: "2026-08-25T13:27:16.336Z",
  }
];
