export type VisualCode = {
  id: string;
  group: string;
  code: string;
  title: string;
  image: string;
  images: string[];
};

export const VISUAL_CODES: VisualCode[] = [
  {
    id: "001",
    group: "Modernist Systems (001â€“010)",
    code: "/Bauhaus Signal Theatre /rebuild",
    title: "Bauhaus Signal Theatre",
    image: "/uploads/visual-code/001-bauhaus-signal-theatre.jpg",
    images: ["/uploads/visual-code/001-bauhaus-signal-theatre.jpg","/uploads/visual-code/001-bauhaus-signal-theatre-2.jpg","/uploads/visual-code/001-bauhaus-signal-theatre-3.jpg"],
  },
  {
    id: "002",
    group: "Modernist Systems (001â€“010)",
    code: "/Constructivist Rhythm Grid /rebuild",
    title: "Constructivist Rhythm Grid",
    image: "/uploads/visual-code/002-constructivist-rhythm-grid.jpg",
    images: ["/uploads/visual-code/002-constructivist-rhythm-grid.jpg","/uploads/visual-code/002-constructivist-rhythm-grid-2.jpg","/uploads/visual-code/002-constructivist-rhythm-grid-3.jpg"],
  },
  {
    id: "003",
    group: "Modernist Systems (001â€“010)",
    code: "/Dutch Modular Collision /rebuild",
    title: "Dutch Modular Collision",
    image: "/uploads/visual-code/003-dutch-modular-collision.jpg",
    images: ["/uploads/visual-code/003-dutch-modular-collision.jpg","/uploads/visual-code/003-dutch-modular-collision-2.jpg","/uploads/visual-code/003-dutch-modular-collision-3.jpg"],
  },
  {
    id: "004",
    group: "Modernist Systems (001â€“010)",
    code: "/International Grid Sabotage /rebuild",
    title: "International Grid Sabotage",
    image: "/uploads/visual-code/004-international-grid-sabotage.jpg",
    images: ["/uploads/visual-code/004-international-grid-sabotage.jpg","/uploads/visual-code/004-international-grid-sabotage-2.jpg","/uploads/visual-code/004-international-grid-sabotage-3.jpg","/uploads/visual-code/004-international-grid-sabotage-4.jpg"],
  },
  {
    id: "005",
    group: "Modernist Systems (001â€“010)",
    code: "/DeStijl Frequency Theatre /rebuild",
    title: "DeStijl Frequency Theatre",
    image: "/uploads/visual-code/005-destijl-frequency-theatre.jpg",
    images: ["/uploads/visual-code/005-destijl-frequency-theatre.jpg","/uploads/visual-code/005-destijl-frequency-theatre-2.jpg","/uploads/visual-code/005-destijl-frequency-theatre-3.jpg"],
  },
  {
    id: "006",
    group: "Modernist Systems (001â€“010)",
    code: "/Modernist Color Interruption /rebuild",
    title: "Modernist Color Interruption",
    image: "/uploads/visual-code/006-modernist-color-interruption.jpg",
    images: ["/uploads/visual-code/006-modernist-color-interruption.jpg","/uploads/visual-code/006-modernist-color-interruption-2.jpg","/uploads/visual-code/006-modernist-color-interruption-3.jpg"],
  },
  {
    id: "007",
    group: "Modernist Systems (001â€“010)",
    code: "/Geometric Program Assembly /rebuild",
    title: "Geometric Program Assembly",
    image: "/uploads/visual-code/007-geometric-program-assembly.jpg",
    images: ["/uploads/visual-code/007-geometric-program-assembly.jpg","/uploads/visual-code/007-geometric-program-assembly-2.jpg","/uploads/visual-code/007-geometric-program-assembly-3.jpg"],
  },
  {
    id: "008",
    group: "Modernist Systems (001â€“010)",
    code: "/Rational Layout Mutiny /rebuild",
    title: "Rational Layout Mutiny",
    image: "/uploads/visual-code/008-rational-layout-mutiny.png",
    images: ["/uploads/visual-code/008-rational-layout-mutiny.png","/uploads/visual-code/008-rational-layout-mutiny-2.jpg","/uploads/visual-code/008-rational-layout-mutiny-3.jpg"],
  },
  {
    id: "009",
    group: "Modernist Systems (001â€“010)",
    code: "/Minimal Axis Drama /rebuild",
    title: "Minimal Axis Drama",
    image: "/uploads/visual-code/009-minimal-axis-drama.jpg",
    images: ["/uploads/visual-code/009-minimal-axis-drama.jpg","/uploads/visual-code/009-minimal-axis-drama-2.jpg","/uploads/visual-code/009-minimal-axis-drama-3.jpg"],
  },
  {
    id: "010",
    group: "Modernist Systems (001â€“010)",
    code: "/Primary Shape Festival /rebuild",
    title: "Primary Shape Festival",
    image: "",
    images: [],
  },
  {
    id: "011",
    group: "Print Imperfections (011â€“020)",
    code: "/Two Ink Collision /rebuild",
    title: "Two Ink Collision",
    image: "",
    images: [],
  },
  {
    id: "012",
    group: "Print Imperfections (011â€“020)",
    code: "/Misregistered Color Ritual /rebuild",
    title: "Misregistered Color Ritual",
    image: "",
    images: [],
  },
  {
    id: "013",
    group: "Print Imperfections (011â€“020)",
    code: "/Screenprint Texture Riot /rebuild",
    title: "Screenprint Texture Riot",
    image: "",
    images: [],
  },
  {
    id: "014",
    group: "Print Imperfections (011â€“020)",
    code: "/Overprinted Shadow Layers /rebuild",
    title: "Overprinted Shadow Layers",
    image: "",
    images: [],
  },
  {
    id: "015",
    group: "Print Imperfections (011â€“020)",
    code: "/Halftone Noise Carnival /rebuild",
    title: "Halftone Noise Carnival",
    image: "",
    images: [],
  },
  {
    id: "016",
    group: "Print Imperfections (011â€“020)",
    code: "/Fluorescent Ink Collision /rebuild",
    title: "Fluorescent Ink Collision",
    image: "",
    images: [],
  },
  {
    id: "017",
    group: "Print Imperfections (011â€“020)",
    code: "/Soy Ink Fever /rebuild",
    title: "Soy Ink Fever",
    image: "",
    images: [],
  },
  {
    id: "018",
    group: "Print Imperfections (011â€“020)",
    code: "/Stencil Print Frenzy /rebuild",
    title: "Stencil Print Frenzy",
    image: "",
    images: [],
  },
  {
    id: "019",
    group: "Print Imperfections (011â€“020)",
    code: "/Rubber Stamp Orchestra /rebuild",
    title: "Rubber Stamp Orchestra",
    image: "",
    images: [],
  },
  {
    id: "020",
    group: "Print Imperfections (011â€“020)",
    code: "/Letterpress Pressure Drama /rebuild",
    title: "Letterpress Pressure Drama",
    image: "",
    images: [],
  },
  {
    id: "021",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Concrete Basement Ritual /rebuild",
    title: "Concrete Basement Ritual",
    image: "",
    images: [],
  },
  {
    id: "022",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Steel Frame Announcement /rebuild",
    title: "Steel Frame Announcement",
    image: "",
    images: [],
  },
  {
    id: "023",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Warehouse Type Monolith /rebuild",
    title: "Warehouse Type Monolith",
    image: "",
    images: [],
  },
  {
    id: "024",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Raw Cement Cabaret /rebuild",
    title: "Raw Cement Cabaret",
    image: "",
    images: [],
  },
  {
    id: "025",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Industrial Warning System /rebuild",
    title: "Industrial Warning System",
    image: "",
    images: [],
  },
  {
    id: "026",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Scaffold Poster Machine /rebuild",
    title: "Scaffold Poster Machine",
    image: "",
    images: [],
  },
  {
    id: "027",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Utility Label Theatre /rebuild",
    title: "Utility Label Theatre",
    image: "",
    images: [],
  },
  {
    id: "028",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Hazard Stripe Opera /rebuild",
    title: "Hazard Stripe Opera",
    image: "",
    images: [],
  },
  {
    id: "029",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Factory Floor Festival /rebuild",
    title: "Factory Floor Festival",
    image: "",
    images: [],
  },
  {
    id: "030",
    group: "Industrial Brutalism (021â€“030)",
    code: "/Exposed Bolt Graphics /rebuild",
    title: "Exposed Bolt Graphics",
    image: "",
    images: [],
  },
  {
    id: "031",
    group: "Editorial Fashion (031â€“040)",
    code: "/Avant Magazine Spread /rebuild",
    title: "Avant Magazine Spread",
    image: "",
    images: [],
  },
  {
    id: "032",
    group: "Editorial Fashion (031â€“040)",
    code: "/Fashion Editorial Intrusion /rebuild",
    title: "Fashion Editorial Intrusion",
    image: "",
    images: [],
  },
  {
    id: "033",
    group: "Editorial Fashion (031â€“040)",
    code: "/Independent Journal Drama /rebuild",
    title: "Independent Journal Drama",
    image: "",
    images: [],
  },
  {
    id: "034",
    group: "Editorial Fashion (031â€“040)",
    code: "/Artbook Layout Collision /rebuild",
    title: "Artbook Layout Collision",
    image: "",
    images: [],
  },
  {
    id: "035",
    group: "Editorial Fashion (031â€“040)",
    code: "/Curatorial Culture Dispatch /rebuild",
    title: "Curatorial Culture Dispatch",
    image: "",
    images: [],
  },
  {
    id: "036",
    group: "Editorial Fashion (031â€“040)",
    code: "/Oversized Caption Theatre /rebuild",
    title: "Oversized Caption Theatre",
    image: "",
    images: [],
  },
  {
    id: "037",
    group: "Editorial Fashion (031â€“040)",
    code: "/Runway Program Interruption /rebuild",
    title: "Runway Program Interruption",
    image: "",
    images: [],
  },
  {
    id: "038",
    group: "Editorial Fashion (031â€“040)",
    code: "/Glossy Editorial Sabotage /rebuild",
    title: "Glossy Editorial Sabotage",
    image: "",
    images: [],
  },
  {
    id: "039",
    group: "Editorial Fashion (031â€“040)",
    code: "/Literary Review Spectacle /rebuild",
    title: "Literary Review Spectacle",
    image: "",
    images: [],
  },
  {
    id: "040",
    group: "Editorial Fashion (031â€“040)",
    code: "/Photo Essay Festival /rebuild",
    title: "Photo Essay Festival",
    image: "",
    images: [],
  },
  {
    id: "041",
    group: "Collage Ephemera (041â€“050)",
    code: "/Found Receipt Symphony /rebuild",
    title: "Found Receipt Symphony",
    image: "",
    images: [],
  },
  {
    id: "042",
    group: "Collage Ephemera (041â€“050)",
    code: "/Torn Ticket Mosaic /rebuild",
    title: "Torn Ticket Mosaic",
    image: "",
    images: [],
  },
  {
    id: "043",
    group: "Collage Ephemera (041â€“050)",
    code: "/Matchbook Memory Collage /rebuild",
    title: "Matchbook Memory Collage",
    image: "",
    images: [],
  },
  {
    id: "044",
    group: "Collage Ephemera (041â€“050)",
    code: "/Postcard Layer Carnival /rebuild",
    title: "Postcard Layer Carnival",
    image: "",
    images: [],
  },
  {
    id: "045",
    group: "Collage Ephemera (041â€“050)",
    code: "/Stamped Envelope Theatre /rebuild",
    title: "Stamped Envelope Theatre",
    image: "",
    images: [],
  },
  {
    id: "046",
    group: "Collage Ephemera (041â€“050)",
    code: "/Transit Pass Ritual /rebuild",
    title: "Transit Pass Ritual",
    image: "",
    images: [],
  },
  {
    id: "047",
    group: "Collage Ephemera (041â€“050)",
    code: "/Vintage Label Collision /rebuild",
    title: "Vintage Label Collision",
    image: "",
    images: [],
  },
  {
    id: "048",
    group: "Collage Ephemera (041â€“050)",
    code: "/Handbill Scrap Archive /rebuild",
    title: "Handbill Scrap Archive",
    image: "",
    images: [],
  },
  {
    id: "049",
    group: "Collage Ephemera (041â€“050)",
    code: "/Polaroid Ephemera Wall /rebuild",
    title: "Polaroid Ephemera Wall",
    image: "",
    images: [],
  },
  {
    id: "050",
    group: "Collage Ephemera (041â€“050)",
    code: "/Carbon Copy Cabaret /rebuild",
    title: "Carbon Copy Cabaret",
    image: "",
    images: [],
  },
  {
    id: "051",
    group: "Nightlife Neon (051â€“060)",
    code: "/Laser Grid Cabaret /rebuild",
    title: "Laser Grid Cabaret",
    image: "",
    images: [],
  },
  {
    id: "052",
    group: "Nightlife Neon (051â€“060)",
    code: "/Ultraviolet Club Ritual /rebuild",
    title: "Ultraviolet Club Ritual",
    image: "",
    images: [],
  },
  {
    id: "053",
    group: "Nightlife Neon (051â€“060)",
    code: "/Electric Marquee Mirage /rebuild",
    title: "Electric Marquee Mirage",
    image: "",
    images: [],
  },
  {
    id: "054",
    group: "Nightlife Neon (051â€“060)",
    code: "/Acid Light Theatre /rebuild",
    title: "Acid Light Theatre",
    image: "",
    images: [],
  },
  {
    id: "055",
    group: "Nightlife Neon (051â€“060)",
    code: "/Fluorescent Tunnel Festival /rebuild",
    title: "Fluorescent Tunnel Festival",
    image: "",
    images: [],
  },
  {
    id: "056",
    group: "Nightlife Neon (051â€“060)",
    code: "/Midnight Signage Fever /rebuild",
    title: "Midnight Signage Fever",
    image: "",
    images: [],
  },
  {
    id: "057",
    group: "Nightlife Neon (051â€“060)",
    code: "/Neon Shadow Opera /rebuild",
    title: "Neon Shadow Opera",
    image: "",
    images: [],
  },
  {
    id: "058",
    group: "Nightlife Neon (051â€“060)",
    code: "/Luminous Wire Spectacle /rebuild",
    title: "Luminous Wire Spectacle",
    image: "",
    images: [],
  },
  {
    id: "059",
    group: "Nightlife Neon (051â€“060)",
    code: "/Afterhours Color Circuit /rebuild",
    title: "Afterhours Color Circuit",
    image: "",
    images: [],
  },
  {
    id: "060",
    group: "Nightlife Neon (051â€“060)",
    code: "/Blacklight Type Carnival /rebuild",
    title: "Blacklight Type Carnival",
    image: "",
    images: [],
  },
  {
    id: "061",
    group: "Luxury Culture (061â€“070)",
    code: "/Quiet Luxury Theatre /rebuild",
    title: "Quiet Luxury Theatre",
    image: "",
    images: [],
  },
  {
    id: "062",
    group: "Luxury Culture (061â€“070)",
    code: "/Sculpted Serif Campaign /rebuild",
    title: "Sculpted Serif Campaign",
    image: "",
    images: [],
  },
  {
    id: "063",
    group: "Luxury Culture (061â€“070)",
    code: "/Velvet Gallery Invitation /rebuild",
    title: "Velvet Gallery Invitation",
    image: "",
    images: [],
  },
  {
    id: "064",
    group: "Luxury Culture (061â€“070)",
    code: "/Marble Culture Announcement /rebuild",
    title: "Marble Culture Announcement",
    image: "",
    images: [],
  },
  {
    id: "065",
    group: "Luxury Culture (061â€“070)",
    code: "/Gilded Minimal Spectacle /rebuild",
    title: "Gilded Minimal Spectacle",
    image: "",
    images: [],
  },
  {
    id: "066",
    group: "Luxury Culture (061â€“070)",
    code: "/Fashion House Program /rebuild",
    title: "Fashion House Program",
    image: "",
    images: [],
  },
  {
    id: "067",
    group: "Luxury Culture (061â€“070)",
    code: "/Perfume Campaign Drama /rebuild",
    title: "Perfume Campaign Drama",
    image: "",
    images: [],
  },
  {
    id: "068",
    group: "Luxury Culture (061â€“070)",
    code: "/Silk Shadow Typography /rebuild",
    title: "Silk Shadow Typography",
    image: "",
    images: [],
  },
  {
    id: "069",
    group: "Luxury Culture (061â€“070)",
    code: "/Ivory Space Cabaret /rebuild",
    title: "Ivory Space Cabaret",
    image: "",
    images: [],
  },
  {
    id: "070",
    group: "Luxury Culture (061â€“070)",
    code: "/Editorial Gold Restraint /rebuild",
    title: "Editorial Gold Restraint",
    image: "",
    images: [],
  },
  {
    id: "071",
    group: "Zine Underground (071â€“080)",
    code: "/Stapled Punk Dispatch /rebuild",
    title: "Stapled Punk Dispatch",
    image: "",
    images: [],
  },
  {
    id: "072",
    group: "Zine Underground (071â€“080)",
    code: "/Basement Xerox Riot /rebuild",
    title: "Basement Xerox Riot",
    image: "",
    images: [],
  },
  {
    id: "073",
    group: "Zine Underground (071â€“080)",
    code: "/Cutpaste Type Insurrection /rebuild",
    title: "Cutpaste Type Insurrection",
    image: "",
    images: [],
  },
  {
    id: "074",
    group: "Zine Underground (071â€“080)",
    code: "/Marker Pen Manifesto /rebuild",
    title: "Marker Pen Manifesto",
    image: "",
    images: [],
  },
  {
    id: "075",
    group: "Zine Underground (071â€“080)",
    code: "/Anarchic Flyer Wall /rebuild",
    title: "Anarchic Flyer Wall",
    image: "",
    images: [],
  },
  {
    id: "076",
    group: "Zine Underground (071â€“080)",
    code: "/Duct Tape Typography /rebuild",
    title: "Duct Tape Typography",
    image: "",
    images: [],
  },
  {
    id: "077",
    group: "Zine Underground (071â€“080)",
    code: "/Garage Gig Debris /rebuild",
    title: "Garage Gig Debris",
    image: "",
    images: [],
  },
  {
    id: "078",
    group: "Zine Underground (071â€“080)",
    code: "/Ransom Letter Cabaret /rebuild",
    title: "Ransom Letter Cabaret",
    image: "",
    images: [],
  },
  {
    id: "079",
    group: "Zine Underground (071â€“080)",
    code: "/DIY Culture Detonation /rebuild",
    title: "DIY Culture Detonation",
    image: "",
    images: [],
  },
  {
    id: "080",
    group: "Zine Underground (071â€“080)",
    code: "/Scrawled Margin Noise /rebuild",
    title: "Scrawled Margin Noise",
    image: "",
    images: [],
  },
  {
    id: "081",
    group: "Cinematic Photography (081â€“090)",
    code: "/Anamorphic Stage Silence /rebuild",
    title: "Anamorphic Stage Silence",
    image: "",
    images: [],
  },
  {
    id: "082",
    group: "Cinematic Photography (081â€“090)",
    code: "/Film Noir Cabaret /rebuild",
    title: "Film Noir Cabaret",
    image: "",
    images: [],
  },
  {
    id: "083",
    group: "Cinematic Photography (081â€“090)",
    code: "/Backstage Flash Diary /rebuild",
    title: "Backstage Flash Diary",
    image: "",
    images: [],
  },
  {
    id: "084",
    group: "Cinematic Photography (081â€“090)",
    code: "/Concert Grain Reverie /rebuild",
    title: "Concert Grain Reverie",
    image: "",
    images: [],
  },
  {
    id: "085",
    group: "Cinematic Photography (081â€“090)",
    code: "/Spotlight Smoke Portrait /rebuild",
    title: "Spotlight Smoke Portrait",
    image: "",
    images: [],
  },
  {
    id: "086",
    group: "Cinematic Photography (081â€“090)",
    code: "/Documentary Crowd Surge /rebuild",
    title: "Documentary Crowd Surge",
    image: "",
    images: [],
  },
  {
    id: "087",
    group: "Cinematic Photography (081â€“090)",
    code: "/Cinema Lobby Mystery /rebuild",
    title: "Cinema Lobby Mystery",
    image: "",
    images: [],
  },
  {
    id: "088",
    group: "Cinematic Photography (081â€“090)",
    code: "/Thirtyfive Millimeter Night /rebuild",
    title: "Thirtyfive Millimeter Night",
    image: "",
    images: [],
  },
  {
    id: "089",
    group: "Cinematic Photography (081â€“090)",
    code: "/Widescreen Venue Memory /rebuild",
    title: "Widescreen Venue Memory",
    image: "",
    images: [],
  },
  {
    id: "090",
    group: "Cinematic Photography (081â€“090)",
    code: "/Director Cut Poster /rebuild",
    title: "Director Cut Poster",
    image: "",
    images: [],
  },
  {
    id: "091",
    group: "Historical Glamour (091â€“100)",
    code: "/Deco Cinema Voltage /rebuild",
    title: "Deco Cinema Voltage",
    image: "",
    images: [],
  },
  {
    id: "092",
    group: "Historical Glamour (091â€“100)",
    code: "/Bauhaus Cabaret Revival /rebuild",
    title: "Bauhaus Cabaret Revival",
    image: "",
    images: [],
  },
  {
    id: "093",
    group: "Historical Glamour (091â€“100)",
    code: "/Victorian Circus Modernism /rebuild",
    title: "Victorian Circus Modernism",
    image: "",
    images: [],
  },
  {
    id: "094",
    group: "Historical Glamour (091â€“100)",
    code: "/BelleEpoque Night Theatre /rebuild",
    title: "BelleEpoque Night Theatre",
    image: "",
    images: [],
  },
  {
    id: "095",
    group: "Historical Glamour (091â€“100)",
    code: "/Streamline Moderne Night /rebuild",
    title: "Streamline Moderne Night",
    image: "",
    images: [],
  },
  {
    id: "096",
    group: "Historical Glamour (091â€“100)",
    code: "/Jazz Age Geometry /rebuild",
    title: "Jazz Age Geometry",
    image: "",
    images: [],
  },
  {
    id: "097",
    group: "Historical Glamour (091â€“100)",
    code: "/Weimar Theatre Fever /rebuild",
    title: "Weimar Theatre Fever",
    image: "",
    images: [],
  },
  {
    id: "098",
    group: "Historical Glamour (091â€“100)",
    code: "/Gilded Cabaret Machine /rebuild",
    title: "Gilded Cabaret Machine",
    image: "",
    images: [],
  },
  {
    id: "099",
    group: "Historical Glamour (091â€“100)",
    code: "/Silent Film Spectacle /rebuild",
    title: "Silent Film Spectacle",
    image: "",
    images: [],
  },
  {
    id: "100",
    group: "Historical Glamour (091â€“100)",
    code: "/Midcentury Lounge Drama /rebuild",
    title: "Midcentury Lounge Drama",
    image: "",
    images: [],
  },
  {
    id: "101",
    group: "Sports Broadcast (101â€“110)",
    code: "/Stadium Scoreboard Cabaret /rebuild",
    title: "Stadium Scoreboard Cabaret",
    image: "",
    images: [],
  },
  {
    id: "102",
    group: "Sports Broadcast (101â€“110)",
    code: "/Boxing Poster Culture /rebuild",
    title: "Boxing Poster Culture",
    image: "",
    images: [],
  },
  {
    id: "103",
    group: "Sports Broadcast (101â€“110)",
    code: "/Halftime Graphic Frenzy /rebuild",
    title: "Halftime Graphic Frenzy",
    image: "",
    images: [],
  },
  {
    id: "104",
    group: "Sports Broadcast (101â€“110)",
    code: "/Racing Stripe Theatre /rebuild",
    title: "Racing Stripe Theatre",
    image: "",
    images: [],
  },
  {
    id: "105",
    group: "Sports Broadcast (101â€“110)",
    code: "/Varsity Type Spectacle /rebuild",
    title: "Varsity Type Spectacle",
    image: "",
    images: [],
  },
  {
    id: "106",
    group: "Sports Broadcast (101â€“110)",
    code: "/Scorecard Event Drama /rebuild",
    title: "Scorecard Event Drama",
    image: "",
    images: [],
  },
  {
    id: "107",
    group: "Sports Broadcast (101â€“110)",
    code: "/Arena Broadcast Collision /rebuild",
    title: "Arena Broadcast Collision",
    image: "",
    images: [],
  },
  {
    id: "108",
    group: "Sports Broadcast (101â€“110)",
    code: "/Televised Match Aesthetic /rebuild",
    title: "Televised Match Aesthetic",
    image: "",
    images: [],
  },
  {
    id: "109",
    group: "Sports Broadcast (101â€“110)",
    code: "/Championship Poster Noise /rebuild",
    title: "Championship Poster Noise",
    image: "",
    images: [],
  },
  {
    id: "110",
    group: "Sports Broadcast (101â€“110)",
    code: "/Athletic Program Remix /rebuild",
    title: "Athletic Program Remix",
    image: "",
    images: [],
  },
  {
    id: "111",
    group: "Material Typography (111â€“120)",
    code: "/Inflatable Letter Theatre /rebuild",
    title: "Inflatable Letter Theatre",
    image: "",
    images: [],
  },
  {
    id: "112",
    group: "Material Typography (111â€“120)",
    code: "/Chrome Type Monument /rebuild",
    title: "Chrome Type Monument",
    image: "",
    images: [],
  },
  {
    id: "113",
    group: "Material Typography (111â€“120)",
    code: "/Paper Fold Typography /rebuild",
    title: "Paper Fold Typography",
    image: "",
    images: [],
  },
  {
    id: "114",
    group: "Material Typography (111â€“120)",
    code: "/Liquid Letter Sculpture /rebuild",
    title: "Liquid Letter Sculpture",
    image: "",
    images: [],
  },
  {
    id: "115",
    group: "Material Typography (111â€“120)",
    code: "/Foam Block Festival /rebuild",
    title: "Foam Block Festival",
    image: "",
    images: [],
  },
  {
    id: "116",
    group: "Material Typography (111â€“120)",
    code: "/Glass Type Illusion /rebuild",
    title: "Glass Type Illusion",
    image: "",
    images: [],
  },
  {
    id: "117",
    group: "Material Typography (111â€“120)",
    code: "/Clay Letter Cabaret /rebuild",
    title: "Clay Letter Cabaret",
    image: "",
    images: [],
  },
  {
    id: "118",
    group: "Material Typography (111â€“120)",
    code: "/Fabric Word Architecture /rebuild",
    title: "Fabric Word Architecture",
    image: "",
    images: [],
  },
  {
    id: "119",
    group: "Material Typography (111â€“120)",
    code: "/Wireframe Type Machine /rebuild",
    title: "Wireframe Type Machine",
    image: "",
    images: [],
  },
  {
    id: "120",
    group: "Material Typography (111â€“120)",
    code: "/Balloon Font Ritual /rebuild",
    title: "Balloon Font Ritual",
    image: "",
    images: [],
  },
  {
    id: "121",
    group: "Street Activism (121â€“130)",
    code: "/Wheatpaste Culture Revolt /rebuild",
    title: "Wheatpaste Culture Revolt",
    image: "",
    images: [],
  },
  {
    id: "122",
    group: "Street Activism (121â€“130)",
    code: "/Stencil Wall Broadcast /rebuild",
    title: "Stencil Wall Broadcast",
    image: "",
    images: [],
  },
  {
    id: "123",
    group: "Street Activism (121â€“130)",
    code: "/Protest Banner Theatre /rebuild",
    title: "Protest Banner Theatre",
    image: "",
    images: [],
  },
  {
    id: "124",
    group: "Street Activism (121â€“130)",
    code: "/Graffiti Type Assembly /rebuild",
    title: "Graffiti Type Assembly",
    image: "",
    images: [],
  },
  {
    id: "125",
    group: "Street Activism (121â€“130)",
    code: "/Street Pole Manifesto /rebuild",
    title: "Street Pole Manifesto",
    image: "",
    images: [],
  },
  {
    id: "126",
    group: "Street Activism (121â€“130)",
    code: "/Pasteup Poster Storm /rebuild",
    title: "Pasteup Poster Storm",
    image: "",
    images: [],
  },
  {
    id: "127",
    group: "Street Activism (121â€“130)",
    code: "/Chalk Pavement Program /rebuild",
    title: "Chalk Pavement Program",
    image: "",
    images: [],
  },
  {
    id: "128",
    group: "Street Activism (121â€“130)",
    code: "/Megaphone Graphic System /rebuild",
    title: "Megaphone Graphic System",
    image: "",
    images: [],
  },
  {
    id: "129",
    group: "Street Activism (121â€“130)",
    code: "/Spraypaint Civic Cabaret /rebuild",
    title: "Spraypaint Civic Cabaret",
    image: "",
    images: [],
  },
  {
    id: "130",
    group: "Street Activism (121â€“130)",
    code: "/Public Notice Mutiny /rebuild",
    title: "Public Notice Mutiny",
    image: "",
    images: [],
  },
  {
    id: "131",
    group: "Museum Institutional (131â€“140)",
    code: "/Curatorial Grid Silence /rebuild",
    title: "Curatorial Grid Silence",
    image: "",
    images: [],
  },
  {
    id: "132",
    group: "Museum Institutional (131â€“140)",
    code: "/Archive Room Typography /rebuild",
    title: "Archive Room Typography",
    image: "",
    images: [],
  },
  {
    id: "133",
    group: "Museum Institutional (131â€“140)",
    code: "/Institutional Identity Ritual /rebuild",
    title: "Institutional Identity Ritual",
    image: "",
    images: [],
  },
  {
    id: "134",
    group: "Museum Institutional (131â€“140)",
    code: "/Exhibition Catalog Poster /rebuild",
    title: "Exhibition Catalog Poster",
    image: "",
    images: [],
  },
  {
    id: "135",
    group: "Museum Institutional (131â€“140)",
    code: "/Gallery Wayfinding Drama /rebuild",
    title: "Gallery Wayfinding Drama",
    image: "",
    images: [],
  },
  {
    id: "136",
    group: "Museum Institutional (131â€“140)",
    code: "/Museum Label Monument /rebuild",
    title: "Museum Label Monument",
    image: "",
    images: [],
  },
  {
    id: "137",
    group: "Museum Institutional (131â€“140)",
    code: "/White Cube Announcement /rebuild",
    title: "White Cube Announcement",
    image: "",
    images: [],
  },
  {
    id: "138",
    group: "Museum Institutional (131â€“140)",
    code: "/Collection Index Theatre /rebuild",
    title: "Collection Index Theatre",
    image: "",
    images: [],
  },
  {
    id: "139",
    group: "Museum Institutional (131â€“140)",
    code: "/Conservation File Aesthetic /rebuild",
    title: "Conservation File Aesthetic",
    image: "",
    images: [],
  },
  {
    id: "140",
    group: "Museum Institutional (131â€“140)",
    code: "/Artifact Caption System /rebuild",
    title: "Artifact Caption System",
    image: "",
    images: [],
  },
  {
    id: "141",
    group: "Surreal Spatial (141â€“150)",
    code: "/Impossible Venue Portal /rebuild",
    title: "Impossible Venue Portal",
    image: "",
    images: [],
  },
  {
    id: "142",
    group: "Surreal Spatial (141â€“150)",
    code: "/Floating Stage Dream /rebuild",
    title: "Floating Stage Dream",
    image: "",
    images: [],
  },
  {
    id: "143",
    group: "Surreal Spatial (141â€“150)",
    code: "/Melting Marquee Architecture /rebuild",
    title: "Melting Marquee Architecture",
    image: "",
    images: [],
  },
  {
    id: "144",
    group: "Surreal Spatial (141â€“150)",
    code: "/Endless Staircase Cabaret /rebuild",
    title: "Endless Staircase Cabaret",
    image: "",
    images: [],
  },
  {
    id: "145",
    group: "Surreal Spatial (141â€“150)",
    code: "/Giant Microphone Landscape /rebuild",
    title: "Giant Microphone Landscape",
    image: "",
    images: [],
  },
  {
    id: "146",
    group: "Surreal Spatial (141â€“150)",
    code: "/Folded City Theatre /rebuild",
    title: "Folded City Theatre",
    image: "",
    images: [],
  },
  {
    id: "147",
    group: "Surreal Spatial (141â€“150)",
    code: "/Gravity Defying Festival /rebuild",
    title: "Gravity Defying Festival",
    image: "",
    images: [],
  },
  {
    id: "148",
    group: "Surreal Spatial (141â€“150)",
    code: "/Miniature Crowd Universe /rebuild",
    title: "Miniature Crowd Universe",
    image: "",
    images: [],
  },
  {
    id: "149",
    group: "Surreal Spatial (141â€“150)",
    code: "/Stage Inside Stage /rebuild",
    title: "Stage Inside Stage",
    image: "",
    images: [],
  },
  {
    id: "150",
    group: "Surreal Spatial (141â€“150)",
    code: "/Cloud Auditorium Mirage /rebuild",
    title: "Cloud Auditorium Mirage",
    image: "",
    images: [],
  },
  {
    id: "151",
    group: "Global Print Traditions (151â€“160)",
    code: "/Korean Poster Rhythm /rebuild",
    title: "Korean Poster Rhythm",
    image: "",
    images: [],
  },
  {
    id: "152",
    group: "Global Print Traditions (151â€“160)",
    code: "/Chinese Opera Ephemera /rebuild",
    title: "Chinese Opera Ephemera",
    image: "",
    images: [],
  },
  {
    id: "153",
    group: "Global Print Traditions (151â€“160)",
    code: "/Polish Theatre Dream /rebuild",
    title: "Polish Theatre Dream",
    image: "",
    images: [],
  },
  {
    id: "154",
    group: "Global Print Traditions (151â€“160)",
    code: "/Cuban Screenprint Festival /rebuild",
    title: "Cuban Screenprint Festival",
    image: "",
    images: [],
  },
  {
    id: "155",
    group: "Global Print Traditions (151â€“160)",
    code: "/Mexican Woodcut Cabaret /rebuild",
    title: "Mexican Woodcut Cabaret",
    image: "",
    images: [],
  },
  {
    id: "156",
    group: "Global Print Traditions (151â€“160)",
    code: "/Indian Matchbox Modernism /rebuild",
    title: "Indian Matchbox Modernism",
    image: "",
    images: [],
  },
  {
    id: "157",
    group: "Global Print Traditions (151â€“160)",
    code: "/Soviet Circus Montage /rebuild",
    title: "Soviet Circus Montage",
    image: "",
    images: [],
  },
  {
    id: "158",
    group: "Global Print Traditions (151â€“160)",
    code: "/French Newwave Flyer /rebuild",
    title: "French Newwave Flyer",
    image: "",
    images: [],
  },
  {
    id: "159",
    group: "Global Print Traditions (151â€“160)",
    code: "/Italian Futurist Night /rebuild",
    title: "Italian Futurist Night",
    image: "",
    images: [],
  },
  {
    id: "160",
    group: "Global Print Traditions (151â€“160)",
    code: "/Brazilian Tropical Modernism /rebuild",
    title: "Brazilian Tropical Modernism",
    image: "",
    images: [],
  },
  {
    id: "161",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Holographic Club Artifact /rebuild",
    title: "Holographic Club Artifact",
    image: "",
    images: [],
  },
  {
    id: "162",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Liquid Chrome Festival /rebuild",
    title: "Liquid Chrome Festival",
    image: "",
    images: [],
  },
  {
    id: "163",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Y2K Interface Cabaret /rebuild",
    title: "Y2K Interface Cabaret",
    image: "",
    images: [],
  },
  {
    id: "164",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Cybernetic Poster Relic /rebuild",
    title: "Cybernetic Poster Relic",
    image: "",
    images: [],
  },
  {
    id: "165",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Iridescent Type Portal /rebuild",
    title: "Iridescent Type Portal",
    image: "",
    images: [],
  },
  {
    id: "166",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Digital Plastic Nostalgia /rebuild",
    title: "Digital Plastic Nostalgia",
    image: "",
    images: [],
  },
  {
    id: "167",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Metallic Gradient Ritual /rebuild",
    title: "Metallic Gradient Ritual",
    image: "",
    images: [],
  },
  {
    id: "168",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Wireframe Rave System /rebuild",
    title: "Wireframe Rave System",
    image: "",
    images: [],
  },
  {
    id: "169",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Pixel Bloom Theatre /rebuild",
    title: "Pixel Bloom Theatre",
    image: "",
    images: [],
  },
  {
    id: "170",
    group: "Digital Chrome Future (161â€“170)",
    code: "/Synthetic Glass Typography /rebuild",
    title: "Synthetic Glass Typography",
    image: "",
    images: [],
  },
  {
    id: "171",
    group: "Folk Craft (171â€“180)",
    code: "/Embroidered Festival Story /rebuild",
    title: "Embroidered Festival Story",
    image: "",
    images: [],
  },
  {
    id: "172",
    group: "Folk Craft (171â€“180)",
    code: "/Woodcut Village Cabaret /rebuild",
    title: "Woodcut Village Cabaret",
    image: "",
    images: [],
  },
  {
    id: "173",
    group: "Folk Craft (171â€“180)",
    code: "/Quilted Poster Geometry /rebuild",
    title: "Quilted Poster Geometry",
    image: "",
    images: [],
  },
  {
    id: "174",
    group: "Folk Craft (171â€“180)",
    code: "/Naive Painting Theatre /rebuild",
    title: "Naive Painting Theatre",
    image: "",
    images: [],
  },
  {
    id: "175",
    group: "Folk Craft (171â€“180)",
    code: "/Ceramic Tile Announcement /rebuild",
    title: "Ceramic Tile Announcement",
    image: "",
    images: [],
  },
  {
    id: "176",
    group: "Folk Craft (171â€“180)",
    code: "/Handcarved Letter Ritual /rebuild",
    title: "Handcarved Letter Ritual",
    image: "",
    images: [],
  },
  {
    id: "177",
    group: "Folk Craft (171â€“180)",
    code: "/Papercut Folk Narrative /rebuild",
    title: "Papercut Folk Narrative",
    image: "",
    images: [],
  },
  {
    id: "178",
    group: "Folk Craft (171â€“180)",
    code: "/Applique Culture Night /rebuild",
    title: "Applique Culture Night",
    image: "",
    images: [],
  },
  {
    id: "179",
    group: "Folk Craft (171â€“180)",
    code: "/Blockprint Myth Festival /rebuild",
    title: "Blockprint Myth Festival",
    image: "",
    images: [],
  },
  {
    id: "180",
    group: "Folk Craft (171â€“180)",
    code: "/Painted Sign Tradition /rebuild",
    title: "Painted Sign Tradition",
    image: "",
    images: [],
  },
  {
    id: "181",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Tabloid Culture Shock /rebuild",
    title: "Tabloid Culture Shock",
    image: "",
    images: [],
  },
  {
    id: "182",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Broadsheet Theatre Edition /rebuild",
    title: "Broadsheet Theatre Edition",
    image: "",
    images: [],
  },
  {
    id: "183",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Front Page Cabaret /rebuild",
    title: "Front Page Cabaret",
    image: "",
    images: [],
  },
  {
    id: "184",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Breaking News Festival /rebuild",
    title: "Breaking News Festival",
    image: "",
    images: [],
  },
  {
    id: "185",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Classified Ad Spectacle /rebuild",
    title: "Classified Ad Spectacle",
    image: "",
    images: [],
  },
  {
    id: "186",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Editorial Column Riot /rebuild",
    title: "Editorial Column Riot",
    image: "",
    images: [],
  },
  {
    id: "187",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Pressroom Ink Drama /rebuild",
    title: "Pressroom Ink Drama",
    image: "",
    images: [],
  },
  {
    id: "188",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Late Edition Night /rebuild",
    title: "Late Edition Night",
    image: "",
    images: [],
  },
  {
    id: "189",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Sunday Supplement Theatre /rebuild",
    title: "Sunday Supplement Theatre",
    image: "",
    images: [],
  },
  {
    id: "190",
    group: "Newspaper Publishing (181â€“190)",
    code: "/Headline Banner Collision /rebuild",
    title: "Headline Banner Collision",
    image: "",
    images: [],
  },
  {
    id: "191",
    group: "Motion Optical (191â€“200)",
    code: "/Velocity Type Storm /rebuild",
    title: "Velocity Type Storm",
    image: "",
    images: [],
  },
  {
    id: "192",
    group: "Motion Optical (191â€“200)",
    code: "/Spinning Letter Orbit /rebuild",
    title: "Spinning Letter Orbit",
    image: "",
    images: [],
  },
  {
    id: "193",
    group: "Motion Optical (191â€“200)",
    code: "/Longexposure Type Trails /rebuild",
    title: "Longexposure Type Trails",
    image: "",
    images: [],
  },
  {
    id: "194",
    group: "Motion Optical (191â€“200)",
    code: "/Elastic Word Collision /rebuild",
    title: "Elastic Word Collision",
    image: "",
    images: [],
  },
  {
    id: "195",
    group: "Motion Optical (191â€“200)",
    code: "/Motion Blur Cabaret /rebuild",
    title: "Motion Blur Cabaret",
    image: "",
    images: [],
  },
  {
    id: "196",
    group: "Motion Optical (191â€“200)",
    code: "/Sequential Type Echoes /rebuild",
    title: "Sequential Type Echoes",
    image: "",
    images: [],
  },
  {
    id: "197",
    group: "Motion Optical (191â€“200)",
    code: "/Stroboscopic Poster Rhythm /rebuild",
    title: "Stroboscopic Poster Rhythm",
    image: "",
    images: [],
  },
  {
    id: "198",
    group: "Motion Optical (191â€“200)",
    code: "/Rotating Grid Festival /rebuild",
    title: "Rotating Grid Festival",
    image: "",
    images: [],
  },
  {
    id: "199",
    group: "Motion Optical (191â€“200)",
    code: "/Typographic Speed Tunnel /rebuild",
    title: "Typographic Speed Tunnel",
    image: "",
    images: [],
  },
  {
    id: "200",
    group: "Motion Optical (191â€“200)",
    code: "/Zoom Burst Theatre /rebuild",
    title: "Zoom Burst Theatre",
    image: "",
    images: [],
  },
  {
    id: "201",
    group: "Systematic & Swiss (201-210)",
    code: "/Swiss Typographic Precision /rebuild",
    title: "Swiss Typographic Precision",
    image: "",
    images: [],
  },
  {
    id: "202",
    group: "Systematic & Swiss (201-210)",
    code: "/International Typographic Order /rebuild",
    title: "International Typographic Order",
    image: "",
    images: [],
  },
  {
    id: "203",
    group: "Systematic & Swiss (201-210)",
    code: "/Acid Graphic Systems /rebuild",
    title: "Acid Graphic Systems",
    image: "",
    images: [],
  },
  {
    id: "204",
    group: "Systematic & Swiss (201-210)",
    code: "/Neo-Memphis Geometry /rebuild",
    title: "Neo-Memphis Geometry",
    image: "",
    images: [],
  },
  {
    id: "205",
    group: "Systematic & Swiss (201-210)",
    code: "/Op-Art Interference /rebuild",
    title: "Op-Art Interference",
    image: "",
    images: [],
  },
  {
    id: "206",
    group: "Systematic & Swiss (201-210)",
    code: "/Isometric Information Theatre /rebuild",
    title: "Isometric Information Theatre",
    image: "",
    images: [],
  },
  {
    id: "207",
    group: "Systematic & Swiss (201-210)",
    code: "/Technical Blueprint Drama /rebuild",
    title: "Technical Blueprint Drama",
    image: "",
    images: [],
  },
  {
    id: "208",
    group: "Systematic & Swiss (201-210)",
    code: "/Architectural Diagram Festival /rebuild",
    title: "Architectural Diagram Festival",
    image: "",
    images: [],
  },
  {
    id: "209",
    group: "Systematic & Swiss (201-210)",
    code: "/Scientific Illustration Spectacle /rebuild",
    title: "Scientific Illustration Spectacle",
    image: "",
    images: [],
  },
  {
    id: "210",
    group: "Systematic & Swiss (201-210)",
    code: "/Medical Archive Poster /rebuild",
    title: "Medical Archive Poster",
    image: "",
    images: [],
  },
  {
    id: "211",
    group: "Reproduction & Photostat (211-220)",
    code: "/Risograph Color Drift /rebuild",
    title: "Risograph Color Drift",
    image: "",
    images: [],
  },
  {
    id: "212",
    group: "Reproduction & Photostat (211-220)",
    code: "/Duotone Photocopy Fever /rebuild",
    title: "Duotone Photocopy Fever",
    image: "",
    images: [],
  },
  {
    id: "213",
    group: "Reproduction & Photostat (211-220)",
    code: "/Newsprint Misprint Ritual /rebuild",
    title: "Newsprint Misprint Ritual",
    image: "",
    images: [],
  },
  {
    id: "214",
    group: "Reproduction & Photostat (211-220)",
    code: "/Thermal Receipt Graphics /rebuild",
    title: "Thermal Receipt Graphics",
    image: "",
    images: [],
  },
  {
    id: "215",
    group: "Reproduction & Photostat (211-220)",
    code: "/Carbon Paper Ghosting /rebuild",
    title: "Carbon Paper Ghosting",
    image: "",
    images: [],
  },
  {
    id: "216",
    group: "Reproduction & Photostat (211-220)",
    code: "/Fax Machine Artifact /rebuild",
    title: "Fax Machine Artifact",
    image: "",
    images: [],
  },
  {
    id: "217",
    group: "Reproduction & Photostat (211-220)",
    code: "/Library Stamp Archive /rebuild",
    title: "Library Stamp Archive",
    image: "",
    images: [],
  },
  {
    id: "218",
    group: "Reproduction & Photostat (211-220)",
    code: "/Manila File Typography /rebuild",
    title: "Manila File Typography",
    image: "",
    images: [],
  },
  {
    id: "219",
    group: "Reproduction & Photostat (211-220)",
    code: "/Office Memo Collision /rebuild",
    title: "Office Memo Collision",
    image: "",
    images: [],
  },
  {
    id: "220",
    group: "Reproduction & Photostat (211-220)",
    code: "/Photostat Culture Riot /rebuild",
    title: "Photostat Culture Riot",
    image: "",
    images: [],
  },
  {
    id: "221",
    group: "Retro Digital (221-230)",
    code: "/Analog Television Broadcast /rebuild",
    title: "Analog Television Broadcast",
    image: "",
    images: [],
  },
  {
    id: "222",
    group: "Retro Digital (221-230)",
    code: "/VHS Tracking Error Theatre /rebuild",
    title: "VHS Tracking Error Theatre",
    image: "",
    images: [],
  },
  {
    id: "223",
    group: "Retro Digital (221-230)",
    code: "/CRT Scanline Spectacle /rebuild",
    title: "CRT Scanline Spectacle",
    image: "",
    images: [],
  },
  {
    id: "224",
    group: "Retro Digital (221-230)",
    code: "/Teletext Graphic System /rebuild",
    title: "Teletext Graphic System",
    image: "",
    images: [],
  },
  {
    id: "225",
    group: "Retro Digital (221-230)",
    code: "/Arcade Cabinet Typography /rebuild",
    title: "Arcade Cabinet Typography",
    image: "",
    images: [],
  },
  {
    id: "226",
    group: "Retro Digital (221-230)",
    code: "/LED Matrix Announcement /rebuild",
    title: "LED Matrix Announcement",
    image: "",
    images: [],
  },
  {
    id: "227",
    group: "Retro Digital (221-230)",
    code: "/Terminal Green Monolith /rebuild",
    title: "Terminal Green Monolith",
    image: "",
    images: [],
  },
  {
    id: "228",
    group: "Retro Digital (221-230)",
    code: "/Dot Matrix Print Drama /rebuild",
    title: "Dot Matrix Print Drama",
    image: "",
    images: [],
  },
  {
    id: "229",
    group: "Retro Digital (221-230)",
    code: "/Computer Manual Aesthetic /rebuild",
    title: "Computer Manual Aesthetic",
    image: "",
    images: [],
  },
  {
    id: "230",
    group: "Retro Digital (221-230)",
    code: "/Operating System Relic /rebuild",
    title: "Operating System Relic",
    image: "",
    images: [],
  },
  {
    id: "231",
    group: "Industrial Technical (231-240)",
    code: "/Industrial Instruction Manual /rebuild",
    title: "Industrial Instruction Manual",
    image: "",
    images: [],
  },
  {
    id: "232",
    group: "Industrial Technical (231-240)",
    code: "/Shipping Label Orchestra /rebuild",
    title: "Shipping Label Orchestra",
    image: "",
    images: [],
  },
  {
    id: "233",
    group: "Industrial Technical (231-240)",
    code: "/Parcel Tape Typography /rebuild",
    title: "Parcel Tape Typography",
    image: "",
    images: [],
  },
  {
    id: "234",
    group: "Industrial Technical (231-240)",
    code: "/Warning Manual Collision /rebuild",
    title: "Warning Manual Collision",
    image: "",
    images: [],
  },
  {
    id: "235",
    group: "Industrial Technical (231-240)",
    code: "/Factory Blueprint Grid /rebuild",
    title: "Factory Blueprint Grid",
    image: "",
    images: [],
  },
  {
    id: "236",
    group: "Industrial Technical (231-240)",
    code: "/Engineering Diagram Riot /rebuild",
    title: "Engineering Diagram Riot",
    image: "",
    images: [],
  },
  {
    id: "237",
    group: "Industrial Technical (231-240)",
    code: "/Mechanical Parts Catalog /rebuild",
    title: "Mechanical Parts Catalog",
    image: "",
    images: [],
  },
  {
    id: "238",
    group: "Industrial Technical (231-240)",
    code: "/Inventory Tag Theatre /rebuild",
    title: "Inventory Tag Theatre",
    image: "",
    images: [],
  },
  {
    id: "239",
    group: "Industrial Technical (231-240)",
    code: "/Toolbox Label System /rebuild",
    title: "Toolbox Label System",
    image: "",
    images: [],
  },
  {
    id: "240",
    group: "Industrial Technical (231-240)",
    code: "/Assembly Manual Spectacle /rebuild",
    title: "Assembly Manual Spectacle",
    image: "",
    images: [],
  },
  {
    id: "241",
    group: "Historical Revival (241-250)",
    code: "/Ancient Manuscript Revival /rebuild",
    title: "Ancient Manuscript Revival",
    image: "",
    images: [],
  },
  {
    id: "242",
    group: "Historical Revival (241-250)",
    code: "/Medieval Illuminated Poster /rebuild",
    title: "Medieval Illuminated Poster",
    image: "",
    images: [],
  },
  {
    id: "243",
    group: "Historical Revival (241-250)",
    code: "/Art Nouveau Botanical Theatre /rebuild",
    title: "Art Nouveau Botanical Theatre",
    image: "",
    images: [],
  },
  {
    id: "244",
    group: "Historical Revival (241-250)",
    code: "/Baroque Announcement Drama /rebuild",
    title: "Baroque Announcement Drama",
    image: "",
    images: [],
  },
  {
    id: "245",
    group: "Historical Revival (241-250)",
    code: "/Renaissance Engraving Collision /rebuild",
    title: "Renaissance Engraving Collision",
    image: "",
    images: [],
  },
  {
    id: "246",
    group: "Historical Revival (241-250)",
    code: "/Neoclassical Civic Monument /rebuild",
    title: "Neoclassical Civic Monument",
    image: "",
    images: [],
  },
  {
    id: "247",
    group: "Historical Revival (241-250)",
    code: "/Rococo Ornament Festival /rebuild",
    title: "Rococo Ornament Festival",
    image: "",
    images: [],
  },
  {
    id: "248",
    group: "Historical Revival (241-250)",
    code: "/Edwardian Print Archive /rebuild",
    title: "Edwardian Print Archive",
    image: "",
    images: [],
  },
  {
    id: "249",
    group: "Historical Revival (241-250)",
    code: "/Victorian Scientific Plate /rebuild",
    title: "Victorian Scientific Plate",
    image: "",
    images: [],
  },
  {
    id: "250",
    group: "Historical Revival (241-250)",
    code: "/Colonial Gazette Revival /rebuild",
    title: "Colonial Gazette Revival",
    image: "",
    images: [],
  },
  {
    id: "251",
    group: "Pixel & Game (251-260)",
    code: "/Pixel Art Monument /rebuild",
    title: "Pixel Art Monument",
    image: "",
    images: [],
  },
  {
    id: "252",
    group: "Pixel & Game (251-260)",
    code: "/8Bit Arcade Ritual /rebuild",
    title: "8Bit Arcade Ritual",
    image: "",
    images: [],
  },
  {
    id: "253",
    group: "Pixel & Game (251-260)",
    code: "/16Bit RPG Poster /rebuild",
    title: "16Bit RPG Poster",
    image: "",
    images: [],
  },
  {
    id: "254",
    group: "Pixel & Game (251-260)",
    code: "/Lowpoly Festival World /rebuild",
    title: "Lowpoly Festival World",
    image: "",
    images: [],
  },
  {
    id: "255",
    group: "Pixel & Game (251-260)",
    code: "/Vector Game Interface /rebuild",
    title: "Vector Game Interface",
    image: "",
    images: [],
  },
  {
    id: "256",
    group: "Pixel & Game (251-260)",
    code: "/Isometric Pixel City /rebuild",
    title: "Isometric Pixel City",
    image: "",
    images: [],
  },
  {
    id: "257",
    group: "Pixel & Game (251-260)",
    code: "/Glitch UI Collapse /rebuild",
    title: "Glitch UI Collapse",
    image: "",
    images: [],
  },
  {
    id: "258",
    group: "Pixel & Game (251-260)",
    code: "/ASCII Terminal Poster /rebuild",
    title: "ASCII Terminal Poster",
    image: "",
    images: [],
  },
  {
    id: "259",
    group: "Pixel & Game (251-260)",
    code: "/Generative Pattern Field /rebuild",
    title: "Generative Pattern Field",
    image: "",
    images: [],
  },
  {
    id: "260",
    group: "Pixel & Game (251-260)",
    code: "/Procedural Geometry Storm /rebuild",
    title: "Procedural Geometry Storm",
    image: "",
    images: [],
  },
  {
    id: "261",
    group: "Map & Data (261-270)",
    code: "/Topographic Map Theatre /rebuild",
    title: "Topographic Map Theatre",
    image: "",
    images: [],
  },
  {
    id: "262",
    group: "Map & Data (261-270)",
    code: "/Weather Chart Spectacle /rebuild",
    title: "Weather Chart Spectacle",
    image: "",
    images: [],
  },
  {
    id: "263",
    group: "Map & Data (261-270)",
    code: "/Constellation Atlas Festival /rebuild",
    title: "Constellation Atlas Festival",
    image: "",
    images: [],
  },
  {
    id: "264",
    group: "Map & Data (261-270)",
    code: "/Transit Diagram Collision /rebuild",
    title: "Transit Diagram Collision",
    image: "",
    images: [],
  },
  {
    id: "265",
    group: "Map & Data (261-270)",
    code: "/Flight Manual Graphics /rebuild",
    title: "Flight Manual Graphics",
    image: "",
    images: [],
  },
  {
    id: "266",
    group: "Map & Data (261-270)",
    code: "/Navigation Chart Drama /rebuild",
    title: "Navigation Chart Drama",
    image: "",
    images: [],
  },
  {
    id: "267",
    group: "Map & Data (261-270)",
    code: "/Geological Survey Archive /rebuild",
    title: "Geological Survey Archive",
    image: "",
    images: [],
  },
  {
    id: "268",
    group: "Map & Data (261-270)",
    code: "/Maritime Signal Poster /rebuild",
    title: "Maritime Signal Poster",
    image: "",
    images: [],
  },
  {
    id: "269",
    group: "Map & Data (261-270)",
    code: "/Cartographic Propaganda /rebuild",
    title: "Cartographic Propaganda",
    image: "",
    images: [],
  },
  {
    id: "270",
    group: "Map & Data (261-270)",
    code: "/Urban Planning Blueprint /rebuild",
    title: "Urban Planning Blueprint",
    image: "",
    images: [],
  },
  {
    id: "271",
    group: "Archive & Documentation (271-280)",
    code: "/Photographic Contact Sheet /rebuild",
    title: "Photographic Contact Sheet",
    image: "",
    images: [],
  },
  {
    id: "272",
    group: "Archive & Documentation (271-280)",
    code: "/Passport Archive Grid /rebuild",
    title: "Passport Archive Grid",
    image: "",
    images: [],
  },
  {
    id: "273",
    group: "Archive & Documentation (271-280)",
    code: "/ID Card Bureaucracy /rebuild",
    title: "ID Card Bureaucracy",
    image: "",
    images: [],
  },
  {
    id: "274",
    group: "Archive & Documentation (271-280)",
    code: "/Police Evidence Board /rebuild",
    title: "Police Evidence Board",
    image: "",
    images: [],
  },
  {
    id: "275",
    group: "Archive & Documentation (271-280)",
    code: "/Case File Collage /rebuild",
    title: "Case File Collage",
    image: "",
    images: [],
  },
  {
    id: "276",
    group: "Archive & Documentation (271-280)",
    code: "/Surveillance Archive /rebuild",
    title: "Surveillance Archive",
    image: "",
    images: [],
  },
  {
    id: "277",
    group: "Archive & Documentation (271-280)",
    code: "/Forensic Documentation /rebuild",
    title: "Forensic Documentation",
    image: "",
    images: [],
  },
  {
    id: "278",
    group: "Archive & Documentation (271-280)",
    code: "/Research Laboratory Poster /rebuild",
    title: "Research Laboratory Poster",
    image: "",
    images: [],
  },
  {
    id: "279",
    group: "Archive & Documentation (271-280)",
    code: "/Field Notes Expedition /rebuild",
    title: "Field Notes Expedition",
    image: "",
    images: [],
  },
  {
    id: "280",
    group: "Archive & Documentation (271-280)",
    code: "/Scientific Field Journal /rebuild",
    title: "Scientific Field Journal",
    image: "",
    images: [],
  },
  {
    id: "281",
    group: "Fine Art Movements (281-290)",
    code: "/Monochrome Expressionism /rebuild",
    title: "Monochrome Expressionism",
    image: "",
    images: [],
  },
  {
    id: "282",
    group: "Fine Art Movements (281-290)",
    code: "/Neo-Dada Collision /rebuild",
    title: "Neo-Dada Collision",
    image: "",
    images: [],
  },
  {
    id: "283",
    group: "Fine Art Movements (281-290)",
    code: "/Pop Art Interruption /rebuild",
    title: "Pop Art Interruption",
    image: "",
    images: [],
  },
  {
    id: "284",
    group: "Fine Art Movements (281-290)",
    code: "/Fluxus Instruction Theatre /rebuild",
    title: "Fluxus Instruction Theatre",
    image: "",
    images: [],
  },
  {
    id: "285",
    group: "Fine Art Movements (281-290)",
    code: "/Minimal Conceptual Silence /rebuild",
    title: "Minimal Conceptual Silence",
    image: "",
    images: [],
  },
  {
    id: "286",
    group: "Fine Art Movements (281-290)",
    code: "/Abstract Expressionist Type /rebuild",
    title: "Abstract Expressionist Type",
    image: "",
    images: [],
  },
  {
    id: "287",
    group: "Fine Art Movements (281-290)",
    code: "/Geometric Op Art /rebuild",
    title: "Geometric Op Art",
    image: "",
    images: [],
  },
  {
    id: "288",
    group: "Fine Art Movements (281-290)",
    code: "/Neo-Futurist Manifesto /rebuild",
    title: "Neo-Futurist Manifesto",
    image: "",
    images: [],
  },
  {
    id: "289",
    group: "Fine Art Movements (281-290)",
    code: "/Arte Povera Materialism /rebuild",
    title: "Arte Povera Materialism",
    image: "",
    images: [],
  },
  {
    id: "290",
    group: "Fine Art Movements (281-290)",
    code: "/Conceptual Gallery Notice /rebuild",
    title: "Conceptual Gallery Notice",
    image: "",
    images: [],
  }
];
